name: CI/CD Mail Reader Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    # Mappiamo il segreto a livello di JOB per renderlo accessibile agli IF sottostanti
    env:
      MAIL_IMAP_PASS: ${{ secrets.MAIL_IMAP_PASS }}

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Scarica dipendenze
      run: go mod download

    - name: Esegui Unit Tests (Veloci)
      run: go test -v ./...

    - name: Esegui Integration Tests (PEC/Aruba)
      # Ora controlliamo la variabile d'ambiente 'env', non 'secrets'
      if: env.MAIL_IMAP_PASS != ''
      env:
        MAIL_IMAP_HOST: ${{ secrets.MAIL_IMAP_HOST }}
        MAIL_IMAP_USER: ${{ secrets.MAIL_IMAP_USER }}
        MAIL_IMAP_PASS: ${{ secrets.MAIL_IMAP_PASS }}
      run: go test -v -tags=integration ./internal/service/...

